### ISSUE TITLE
shiboken6_genpyi for the library

### ISSUE THREAD

**Issue by wuyuanyi135** [mborgerson/pyside6_qtads#10]
Hi! 

Thanks for your great work for creating this binding! I wonder if it is possible to use `shiboken6_genpyi` to create the type hint and ship it in the wheel? This will greatly improve the development experience by providing code completion and type checking.

Thanks!

**Comment by mborgerson** [comment]
Yes! I also would like type hints included with the library. @n-elie was working on it as part of #5, so it will likely be included soon

**Comment by wuyuanyi135** [comment]
Fantastic! Looking forward to that
