### ISSUE TITLE
Support for pyside6/shiboken6 6.8.0

### ISSUE THREAD

**Issue by lexnicolaes** [mborgerson/pyside6_qtads#38]
PySide6 6.8.0 contains a number of bugfixes that are relevant for my project, could you please generate a intermediate release with support for this version?

**Comment by plankter** [comment]
There is already version 6.8.0.1...

**Comment by lexnicolaes** [comment]
:-) well that was quick, edited the title

**Comment by mborgerson** [comment]
Will do

**Comment by mborgerson** [comment]
Release tag pushed! Wheels building now
